---
title: "Applying"
---



-   **Are there any registration fees?**

    No. Participation is free. 

-   **Am I eligible to the masterclass?**

    Participation is restricted to graduate students enrolled at UCT.
    
    The priority is given to students enrolled in the MPhil in Southern Urbanism or in the MA in Critical Urbanisms, hosted at the African Centre for Cities at UCT. Arrangements have been made with the directors of these programs to facilitate the involvment of these students and avoid conflicting schedules.

    Application from students enrolled in other MPhil programs at UCT are also welcome. We expect these students to make arrangements in their respective schedule in order to be available for the whole duration of the masterclass. To justify an absence for a course, we can upon request provide an official letter of participation explaning the content of the masterclass and its learning outcomes.

-   **How can I apply and what is the deadline?**

    Fill this online [form](https://forms.gle/XaK6pze9b7QvcN2K6) to apply. Applications are due Wesnesday <ins>12th of March 2023</ins>. 
    
    Participants will be notified of their acceptance by email before the 15th of March 2023. 

-   **How many seats are available?**

    The masterclass can host about 10 students from UCT.

-   **What is expected from me?**

    We expect you to join the masterclass with lots of questions and motivation, collaborate with students coming from France and Nigeria, and get involved for the entire duration of the masterclass. 

    We will provide transport for all activities taking place outside of UCT, either leaving from the upper campus or from the Lenox Guest House, depending on the day's schedule. For the participant-led projects, each group will be allocated a budget to cover travel expenses related to fieldwor.
    
    You will be welcome to join us at the guest house in Gardens for our daily Debrief & Discussion.

-   **But Friday 7th is a public holiday?**

    We are aware of this issue, but to make the most of this masterclass, we expect you to participate this Friday and the following Saturday until mid-afternoon. Sunday 9th and Monday 10th remain days off.
