---
title: "Materials"
---

<br>
The list of references will be updated over the next couple of weeks. 


## Reading

We expect participants to actively read the following papers and chapters ahead of the masterclass in order to familiarize themselves with key concepts and get inspired by the questions and topics these authors examine.

- Anwar, M. A., & Graham, M. (2022). *[The Digital Continent: Placing Africa in Planetary Networks of Work](https://library.oapen.org/handle/20.500.12657/52606)*. Oxford University Press. [*Only prologue and Chapter 2*]

- Bronsvoort, I., & Uitermark, J. L. (2022). "[Seeing the street through Instagram. Digital platforms and the amplification of gentrification](https://journals.sagepub.com/doi/full/10.1177/00420980211046539)". *Urban Studies*, 59(14), 2857–2874.

- Guma, P.K. (2020). "[Incompleteness of urban infrastructures in transition: Scenarios from the mobile age in Nairobi](https://journals.sagepub.com/doi/pdf/10.1177/0306312720927088). *Social Studies of Science*, 50(5), pp.728-750.

<!-- -  Guermond, V. (2022) "[Whose money? Digital remittances, mobile money and fintech in Ghana](https://www.tandfonline.com/doi/full/10.1080/17530350.2021.2018347?src=recsys), *Journal of Cultural Economy*, 15:4, 436-451. -->

<!-- - Pollio A. & Cirolia, L. (2022) "[Fintech urbanism in the startup capital of Africa](https://www.tandfonline.com/doi/full/10.1080/17530350.2022.2058058)", *Journal of Cultural Economy*, 15:4, 508-523. -->


-  Pollio, A. (2020). "[Making the silicon cape of Africa: Tales, theories and the narration of startup urbanism](https://doi.org/10.1177/0042098019884275)", *Urban Studies*, 57(13), 2715--2732.

- Rosen, J. & Alvarez León, LF. (2022) "[The Digital Growth Machine: Urban Change and the Ideology of Technology](https://www.tandfonline.com/doi/full/10.1080/24694452.2022.2052008)", *Annals of the American Association of Geographers*, 112:8, 2248-2265.

- Sadowski, J. (2019). "[When data is capital: Datafication, accumulation, and          extraction](https://doi.org/10.1177/2053951718820549)". *Big Data & Society*, 6(1). 

- Söderström O, Blake E. and Odendaal N. (2022) "[More-than-local, more-than-mobile: The smart city effect in South Africa](https://www.sciencedirect.com/science/article/pii/S0016718521000919)". *Geoforum*, 122: 103–117.


*If you cannot access these references, please reach out to the organisers.*

## Watching and listening

-   Miller, J. [Unequal Scenes: South Africa](https://unequalscenes.com/south-africa)

- Bloomberg, 2023, "[Amazon Battles South African Tribes Over ‘Sacred’ Land](https://www.bloomberg.com/news/videos/2022-12-15/amazon-battles-south-african-tribes-over-sacred-land-video)"



## Miscellaneous

-   Bring i) small notebook and a pen ii) a camera or phone to take notes and/or pictures, iii) your personal laptop, if possible.

-   Take comfortable shoes: we will do a fair amount of walking.

-   Travel adaptors can be easily purchased at the Gardens Shopping Centre next to the Guest House.

-   We recommend that foreign participants purchase a South African SIM card with a small data bundle to facilitate communication and fieldwork during the masterclass. The easiest option to so do is  upon arrival at the Cape Town airport: local companies such as MTN or Vodafone are located immediately at the exit of international arrivals, on the right-hand side. The procedure takes about 10 minutes.


