---
title: "Schedule"
---


The first three days combine guest lectures, workshops and site visits. 

The rest of the masterclass is dedicated to participant-led projects: students will select one of four research topics introduced by the teaching staff, design a collective research protocol, and work in small groups.

On the last afternoon, each group will present the output of their projects to discuss their findings and reflections with the entire cohort.



|                 |                Morning                 |          Afternoon                        |
|:---------------:|:--------------------------------------|:-----------------------------------------|
|   Sunday 2nd    |   | *Participants from France and Nigeria arrive at the [Lenox Guest House](https://thelenox.co.za/).* |
|  Monday 3rd     | 8:30-9:45  Introduction <br><br>   10:00-10:45 Guest speaker: [Edgar Pieterse](https://www.africancentreforcities.net/people/edgar-pieterse/) (ACC)   <br><br> 11:00-12:30 Research workshop. Guest Speaker: [Rike Sitas](https://www.africancentreforcities.net/people/rike-sitas/) (ACC) | 2:00-3:00 Guest speaker: [Kelle Howson](https://www.oii.ox.ac.uk/people/profiles/kelle-howson/) (Oxford-Fairwork)    <br><br>  3:15-4:15 Guest speaker: [Rachel Adams](https://researchictafrica.net/author/rachel-adams/) (Research ICT Africa) <br><br>  5:00-6:00  D&D*                  |
|  Tuesday 4th    | 8:00-10:30 Guest speaker: Ian Thompson, founder of [Toomuchwifi](https://toomuchwifi.co.za/). Venue: [Jordan's](https://www.facebook.com/JordanWaysofCooking/) in Langa. <br><br> 11:00-12:00 Guest speaker: [Nancy Odendaal](https://scholar.google.com/citations?user=AeAAlAoAAAAJ&hl=en) (UCT)            | 1:30-5:00 Visit of [Teraco](https://www.teraco.co.za/)'s [CT2 data centre](https://www.teraco.co.za/data-centre-locations/cape-town/).  <br> <br><br><br>     6:00-6:30   D & D     |
|  Wednesday 5th  | 9:30-10:30 Guest speaker: Antonio Bruni, founder of [Picup Technologies](https://picup.co.za/). <br><br> 11:00-12:00 Guest speaker: [Alicia Fortuin](https://www.africancentreforcities.net/people/alicia-fortuin/) (ACC)              | 2:00-4:00: visit of [French Tech SA](https://www.frenchtechsa.com/), a startup incubator in Century City. <br> <br><br><br>   5:00-5:30 D&D <br>    5:30-6:00 Presentation of research topics
|  Thursday 6th   | Group projects   <br>  <br> 12:00-13:00 [HUMA Seminar](http://www.huma.uct.ac.za/event/julien-migozzi-good-bad-and-data-credit-scoring-and-remaking-post-apartheid-city). Speaker: [Julien Migozzi](https://jmigozzi.github.io/)  (Oxford)    | Group projects   <br><br> <br><br>  5:00-5:30  D&D      |
|  Friday 7th     | Group projects                   | Group projects <br>  <br>  5:00-5:30 D&D          |                  |
|  Saturday 8th   | Group projects          | Group projects  <br>  <br>  5:00-5:30   D&D                       |
|  Sunday 9th     | *Day off*             |                               |
|  Monday 10th    |*Day off*             |                        |
|  Tuesday 11th   | Consolidation              | Consolidation  <br> <br>   5:00-5:30 D&D   |
|  Wednesday 12th | Consolidation                  | 2:00-4:30 Project presentations. <br> 5:00-6:00 Concluding session.    <br> 6:30 Closing braai with [SpitBraaiBoyzZa](https://www.instagram.com/spitbraaiboyz.za/?hl=en).             |
|  Thursday 13th  | *Participants depart*         |                  |

*Please note that this program is subject to minor modifications.*

### Notes


-  (*) Each day will conclude on a Debrief & Discussion (D&D), during which we expect participants to reflect on the day's contents, using their notes to confront their impressions and analysis.

 - Unless specified, all guest lectures and workshops will take place on the UCT campus in the [Centlivres Building](https://goo.gl/maps/Ptpxv3QcnV6yCzGx8) in the south end of the upper campus.

 - Unless specified, every Debrief & Discussion will take place at the Lenox Guest House. Provisions have been taken to allow for UCT students to enter the premises upon presentation of their student cards.

- Friday 7th is a public holiday in South Africa: the masterclass will nonetheless takes place on that day. The following Sunday and Monday will be considered as days off.